version: "3.9"
name: "pricehawk-backend"

services:
  app:
    build: "."
    depends_on:
      - "db"
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - "./:/app"

  scheduler:
    build: "."
    depends_on:
      - "db"
    volumes:
      - "./:/app"
    command: "crond -f -l 2"

  db:
    image: "postgres:15-alpine"
    environment:
      - "POSTGRES_PASSWORD=password"
    volumes:
      - "postgres_data:/var/lib/postgresql/data/"

volumes:
  postgres_data: