version: "3.9"

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - '8000:8000'
    command: bash -c "
          python manage.py migrate 
          && python manage.py runserver 0.0.0.0:8000"
  db:
    image: postgres:13
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    volumes:
      - "postgres_data:/var/lib/postgresql/data/"

volumes:
  postgres_data: