# Generated by Django 4.1.5 on 2023-02-23 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='name_html',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='price_html',
            field=models.TextField(null=True),
        ),
    ]
