# Generated by Django 4.1.7 on 2023-03-28 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_item_vendor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='vendor_name',
            field=models.FloatField(max_length=100, null=True),
        ),
    ]
