# Generated by Django 4.1.5 on 2023-03-29 20:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_phuser_google'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phuser',
            name='priceInterval',
            field=models.FloatField(default=12, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)]),
        ),
    ]
